//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int playerid { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string usesname { get; set; }
        public byte bats { get; set; }
        public byte throws { get; set; }
        public Nullable<short> teamid { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthcity { get; set; }
        public string birthcountry { get; set; }
        public string birthstate { get; set; }
        public Nullable<byte> height { get; set; }
        public Nullable<short> weight { get; set; }
        public byte position { get; set; }
        public Nullable<byte> number { get; set; }
        public string headshoturl { get; set; }
    }
}
