//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyaApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class pstatsplayersseasonsbyteam
    {
        public int playerid { get; set; }
        public short yearid { get; set; }
        public byte levelid { get; set; }
        public short teamid { get; set; }
        public short g { get; set; }
        public short ab { get; set; }
        public short b1 { get; set; }
        public short b2 { get; set; }
        public short b3 { get; set; }
        public short hr { get; set; }
        public short ubb { get; set; }
        public short hbp { get; set; }
        public short so { get; set; }
        public short ibb { get; set; }
        public short sh { get; set; }
        public short sf { get; set; }
        public short pa { get; set; }
        public short r { get; set; }
        public short outs { get; set; }
        public short er { get; set; }
        public short gs { get; set; }
        public short gf { get; set; }
        public short cg { get; set; }
        public short sho { get; set; }
        public short w { get; set; }
        public short l { get; set; }
        public short sv { get; set; }
    }
}
